- name: create teeworlds user
  ansible.builtin.user:
    create_home: true
    home: "{{ teeworlds__install_dir }}"
    name: "{{ teeworlds__user }}"
    system: true

- name: download teeworlds server
  ansible.builtin.unarchive:
    src: "{{ teeworlds__server_url }}"
    remote_src: true
    dest: "{{ teeworlds__install_dir }}/{{ teeworlds__version }}"

- name: link current version
  ansible.builtin.file:
    src: "{{ teeworlds__install_dir }}/current"
    dest: "{{ teeworlds__install_dir }}/{{ teeworlds__version }}"
    owner: teeworlds
    group: teeworlds
    state: link